#!/bin/bash
if ! command -v fping &> /dev/null
then
    yum install fping -y
fi
mkdir -p pre-test shutdown post-test
NOW=$(date +"%m-%d-%Y")
curl -XDELETE localhost:9200/pre-test\*
fping -f hosts.txt > pre-test/result-$NOW.csv
#TOTAL=$(cat round1/result-$NOW.csv | wc -l)
#UP=$(grep "alive" round1/result-$NOW.csv | wc -l)
#DOWN=$(grep "unreachable" round1/result-$NOW.csv | wc -l)
#echo "$UP,$DOWN,$TOTAL"
# sed -i 's/ is /\,/g' round1/result-$NOW.csv
# sed -i '1i ip,state' round1/result-$NOW.csv
