#!/bin/bash
if ! command -v fping &> /dev/null
then
    yum install fping -y
fi
mkdir -p pre-test shutdown post-test
NOW=$(date +"%m-%d-%Y")
curl -XDELETE localhost:9200/shutdown\*
fping -f hosts.txt > shutdown/result-$NOW.csv
# sed -i 's/ is /\,/g' round2/result-$NOW.csv
# sed -i '1i ip,state' round2/result-$NOW.csv
